### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by masterkain** [stevenpall/github-actions#1]
hello,
thanks for the code, I have yet to try it but in the readme I see the github action not defined in yml, whilst github is requiring it for creating an action.

is there a need for update?

**Comment by stevenpall** [comment]
@masterkain Yes, the `flux-pull-request` action needs to be updated to use YAML syntax. I haven't had time to port it over, but I may be able to in the near future. There are probably also some bugfixes and improvements that could be implemented...

**Comment by masterkain** [comment]
so I've tested it quite a bit with the v2 actions api and unfortunately I have an issue.

in the bash script we are fetching `GITHUB_SHA`, but as I can see the returned result cannot be found in the API, because apparently it's the value of a shadowy ref that github uses:

```
From https://github.com/xxx/xxx
 * [new ref]         b9db235aa34e9a7f78bc6c709384a436295d94ed -> pull/9/merge
```

that does not match anything in the current git tree nor API responses:

```
  "head": {
    "label": "xxx:feature/another_test",
    "ref": "feature/another_test",
    "sha": "0ca6c6a791750d7e8034c6130987b431f06f9db1",
```

I'm trying to find a way around that.

This is also interesting https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit

**Comment by masterkain** [comment]
I was able to proceed by setting a custom `CURRENT_SHA: ${{ github.event.pull_request.head.sha }}` and using it in the bash script. Debugging the rest.
